'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PasahitzaAldatu

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''LabelLehenengoPasahitza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLehenengoPasahitza As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxLehenengoPasahitza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxLehenengoPasahitza As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelPasahitzBerria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPasahitzBerria As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxPasahitzBerria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxPasahitzBerria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelPasahitzBerriaBerriro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPasahitzBerriaBerriro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxPasahitzBerriaBerriro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxPasahitzBerriaBerriro As Global.System.Web.UI.WebControls.TextBox
End Class
